# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false


  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/focal64"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/focal64"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8444
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/focal64"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
    vagrant3.vm.network "forwarded_port", guest: 443, host: 8445
  end

  # config.vm.box = "ubuntu/focal64"
  # config.vm.hostname = "testserver"
  # config.vm.network "forwarded_port",
  #   id: 'ssh', guest:22, host: 2202, host_ip: "127.0.0.1", auto_correct: false
  # config.vm.network "forwarded_port",
  #   id: 'http', guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "forwarded_port",
  #   id: 'https', guest: 443, host: 8443, host_ip: "127.0.0.1"

  # if Vagrant.has_plugin?("vagrant-vbguest")
  #   config.vbguest.auto_update = false
  # end

  # config.vm.provider "virtualbox" do |virtualbox|
  #   virtualbox.name = "ch03"
  # end
end
