---
- name: Sync Airflow DAGS
  hosts: airflow-simple

  tasks:
    - name: Register Airflow dags repository
      ansible.builtin.command: airflow config get-value core dags_folder
      register: dags_folder_command

    - name: "Host default gateway validation"
      debug:
        msg: "Dags folder {{ dags_folder_command.stdout }}"

    - name: Create dags folder
      ansible.builtin.file:
        path: "{{ dags_folder_command.stdout }}"
        state: directory

    - name: Sync Repository
      ansible.builtin.git:
        repo: "{{ dags_repository }}"
        dest: "{{ dags_folder_command.stdout }}"
        single_branch: yes
        version: main
        force: yes

    - name: Install DAGs dependencies
      ansible.builtin.pip:
        break_system_packages: true
        requirements: "{{ dags_folder_command.stdout }}/requirements.txt"

    - name: Run DAGs test
      # TODO: Why it does not work without "/usr/bin/python3 -m"? even when interpreter is set on vars.
      ansible.builtin.command: "/usr/bin/python3 -m pytest -v {{ dags_folder_command.stdout }}/labs"
...
