# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_FILE_API_VERSION = "2"

CLUSTER_BASE_IP = "192.168"

ROUTER_INTERFACES = [
  {
    subnet: "subnet60", ip: "#{CLUSTER_BASE_IP}.60.1"
  },
  {
    subnet: "subnet61", ip: "#{CLUSTER_BASE_IP}.61.1"
  },
  {
    subnet: "subnet62", ip: "#{CLUSTER_BASE_IP}.62.1"
  }
]

ZOOKEEPER_ENSEMBLE = [{
    name: "zookeeper1",
    box: "ubuntu/focal64",
    memory: 2048,
    subnet: "subnet60",
    ip: "#{CLUSTER_BASE_IP}.60.10",
    ansible_port: 2200
  },
  {
    name: "zookeeper2",
    box: "ubuntu/focal64",
    memory: 2048,
    subnet: "subnet61",
    ip: "#{CLUSTER_BASE_IP}.61.11",
    ansible_port: 2201
  },
  {
    name: "zookeeper3",
    box: "ubuntu/focal64",
    memory: 2048,
    subnet: "subnet62",
    ip: "#{CLUSTER_BASE_IP}.62.12",
    ansible_port: 2202
  }]

KAFKA_CLUSTER =[{
  name: "kafka1",
  box: "ubuntu/focal64",
  memory: 8192,
  subnet: "subnet60",
  ip: "#{CLUSTER_BASE_IP}.60.20",
  ansible_port: 2203
},
{
  name: "kafka2",
  box: "ubuntu/focal64",
  memory: 8192,
  subnet: "subnet61",
  ip: "#{CLUSTER_BASE_IP}.61.21",
  ansible_port: 2204
},
{
  name: "kafka3",
  box: "ubuntu/focal64",
  memory: 8192,
  subnet: "subnet62",
  ip: "#{CLUSTER_BASE_IP}.62.22",
  ansible_port: 2205
}]

Vagrant.configure(VAGRANT_FILE_API_VERSION) do |config|

  # One key for all hosts - See notes#SSH Config
  config.ssh.insert_key = false

  # Router configuration
  config.vm.define "router" do |router|
    router.vm.box = "ubuntu/focal64"
    router.vm.hostname = "router"

    ROUTER_INTERFACES.each do |interface|
      router.vm.network "private_network", ip: interface[:ip], virtualbox__intnet: interface[:subnet]
    end

    router.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "ha_kafka_router"
      virtualbox.memory = 1024
    end
  end

  # Zookeeper ensemble VMs configuration
  ZOOKEEPER_ENSEMBLE.each do |zookeeper|
    config.vm.define zookeeper[:name] do |zookeeper_conf|
      zookeeper_conf.vm.box = zookeeper[:box]
      zookeeper_conf.vm.hostname = zookeeper[:name]

      zookeeper_conf.vm.network "private_network", ip: zookeeper[:ip], virtualbox__intnet: zookeeper[:subnet]
      zookeeper_conf.vm.network "forwarded_port", id: "ssh", guest: 22, host: zookeeper[:ansible_port]

      zookeeper_conf.vm.provider "virtualbox" do |virtualbox|
        virtualbox.name = zookeeper[:name]
        virtualbox.memory = zookeeper[:memory]
      end
    end
  end

  # Kafka cluster VMs configuration
  KAFKA_CLUSTER.each do |kafka|
    config.vm.define kafka[:name] do |kafka_conf|
      kafka_conf.vm.box = kafka[:box]
      kafka_conf.vm.hostname = kafka[:name]

      kafka_conf.vm.network "private_network", ip: kafka[:ip], virtualbox__intnet: kafka[:subnet]
      kafka_conf.vm.network "forwarded_port", id: "ssh", guest: 22, host: kafka[:ansible_port]

      kafka_conf.vm.provider "virtualbox" do |virtualbox|
        virtualbox.name = kafka[:name]
        virtualbox.memory = kafka[:memory]
      end
    end
  end

  # Kafka UI
  config.vm.define "kafka-drop" do |kafka_ui_conf|
    kafka_ui_conf.vm.box = "ubuntu/focal64"
    kafka_ui_conf.vm.hostname = "kafka-drop"

    kafka_ui_conf.vm.network "private_network", ip: "192.168.60.99", virtualbox__intnet: "subnet60"
    kafka_ui_conf.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2206

    kafka_ui_conf.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "kafka-drop"
      virtualbox.memory = 2048
    end
  end

end
