---
- name: PostgreSQL 16 - Install and Configuration
  hosts: postgreSQL
  become: true
  gather_facts: false

  vars:
    repo_key_dir: /usr/share/postgresql-common/pgdg
    repo_key_name: apt.postgresql.org.asc
    repo_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    ubuntu_codename: focal
    pg_home: /etc/postgresql/16/main/

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.systemd_service:
        name: postgresql
        state: restarted

  tasks:
    - name: Create installation dirs
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ repo_key_dir }}"

    - name: Download repo key
      ansible.builtin.get_url:
        url: "{{ repo_key_url }}"
        dest: "{{ repo_key_dir }}/{{ repo_key_name }}"

    - name: Configure repo
      ansible.builtin.apt_repository:
        filename: pgdg
        repo: "deb [signed-by={{ repo_key_dir }}/{{ repo_key_name }}] https://apt.postgresql.org/pub/repos/apt {{ ubuntu_codename }}-pgdg main"

    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql-16
        state: present

    - name: Copy postgresql.conf
      copy:
        src: postgresql.conf
        dest: "{{ pg_home }}"
        mode: '0644'
      notify: Restart PostgreSQL

    - name: Copy pg_hba.conf
      copy:
        src: pg_hba.conf
        dest: "{{ pg_home }}"
        mode: '0640'
      notify: Restart PostgreSQL

...