---
- name: Setup default PostgreSQl database
  hosts: postgreSQL
  become: true
  gather_facts: false

  vars:
    pg_peer_superuser: postgres
    default_db_name: public
    default_user: labsu

  tasks:
    - name: Install psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present

    - name: Install acl
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Create public database
      community.postgresql.postgresql_db:
        name: "{{default_db_name}}"
      become_user: "{{ pg_peer_superuser }}"

    - name: Create default user
      community.postgresql.postgresql_user:
        db: "{{default_db_name}}"
        name: "{{default_user}}"
        password: "{{default_user}}"
        comment: Labs super user
        role_attr_flags: SUPERUSER
      become_user: "{{ pg_peer_superuser }}"
...