---
- name: HA Kafka router configuration
  hosts: router
  become: true
  gather_facts: false

  tasks:
    - name: Enable ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
...